export interface rederImg{
    size?:string;
}

export const redes = [
  {
  id:1,
  red:"email",
  Url:"info@unimar.edu.ve",
  img:"email.png",
  size:"size-8"
  },  
  {
  id:2,
  red:"facebook",
  Url:"https://www.facebook.com/share/1CJrXgVUPe/",
  img:"facebook.png",
  size:"size-8"
  },  
  {
  id:3,
  red:"instagram",
  Url:"https://www.instagram.com/universidademargarita",
  img:"instagram.png",
  size:"size-8"
  },  
  {
  id:4,
  red:"youtube",
  Url:"https://www.youtube.com/channel/UCnRVkJ1OW2oLN_TpvXAnUyw",
  img:"youtube-03.png",
  size:"size-8"
  },  
  {
  id:5,
  red:"X",
  Url:"https://www.twitter.com/somosunimar",
  img:"gorjeo.png",
  size:"size-8"
  },  
  {
  id:6,
  red:"linkedin",
  Url:"https://www.linkedin.com/company/univdemargarita",
  img:"linkedin.png",
  size:"size-8"
  },  
]